import 'package:association_card_game/models/models.dart';
import 'package:association_card_game/utils/utils.dart';

final List<GameCard> gameCards = [
  GameCard(id: 0, name: 'The sun', image: Images.sun),
  GameCard(id: 1, name: 'Sea', image: Images.sea),
  GameCard(id: 2, name: 'Flowers', image: Images.flowers),
  GameCard(id: 3, name: 'Mountains', image: Images.mountains),
  GameCard(id: 4, name: 'Children', image: Images.children),
  GameCard(id: 5, name: 'Summer', image: Images.summer),
  GameCard(id: 6, name: 'Music', image: Images.music),
  GameCard(id: 7, name: 'Book', image: Images.book),
  GameCard(id: 8, name: 'Travel', image: Images.travel),
  GameCard(id: 9, name: 'Friendship', image: Images.friendship),
  GameCard(id: 10, name: 'Laughter', image: Images.laughter),
  GameCard(id: 11, name: 'Inspiration', image: Images.inspiration),
  GameCard(id: 12, name: 'A kiss', image: Images.kiss),
  GameCard(id: 13, name: 'A wedding', image: Images.wedding),
  GameCard(id: 14, name: 'Sunset', image: Images.sunset),
  GameCard(id: 15, name: 'City', image: Images.city),
  GameCard(id: 16, name: 'Nature', image: Images.nature),
  GameCard(id: 17, name: 'Sport', image: Images.sport),
  GameCard(id: 18, name: 'Health', image: Images.health),
  GameCard(id: 19, name: 'Good food', image: Images.goodFood),
  GameCard(id: 20, name: 'Movie', image: Images.movie),
  GameCard(id: 21, name: 'Excitement', image: Images.excitement),
  GameCard(id: 22, name: 'Lightning', image: Images.lightning),
  GameCard(id: 23, name: 'Phone', image: Images.phone),
  GameCard(id: 24, name: 'Time', image: Images.time),
  GameCard(id: 25, name: 'Melody', image: Images.melody),
  GameCard(id: 26, name: 'Mirror', image: Images.mirror),
  GameCard(id: 27, name: 'Bridge', image: Images.bridge),
  GameCard(id: 28, name: 'Paint', image: Images.paint),
];

const _cards = 'assets/png/cards';
final List<GameCard> otherCards = [
  GameCard(id: 29, name: '', image: "$_cards/card1.png"),
  GameCard(id: 30, name: '', image: "$_cards/card2.png"),
  GameCard(id: 31, name: '', image: "$_cards/card3.png"),
  GameCard(id: 32, name: '', image: "$_cards/card4.png"),
  GameCard(id: 33, name: '', image: "$_cards/card5.png"),
  GameCard(id: 34, name: '', image: "$_cards/card6.png"),
  GameCard(id: 35, name: '', image: "$_cards/card7.png"),
  GameCard(id: 36, name: '', image: "$_cards/card8.png"),
  GameCard(id: 37, name: '', image: "$_cards/card9.png"),
  GameCard(id: 38, name: '', image: "$_cards/card10.png"),
  GameCard(id: 39, name: '', image: "$_cards/card11.png"),
  GameCard(id: 40, name: '', image: "$_cards/card12.png"),
  GameCard(id: 41, name: '', image: "$_cards/card13.png"),
  GameCard(id: 42, name: '', image: "$_cards/card14.png"),
  GameCard(id: 43, name: '', image: "$_cards/card15.png"),
  GameCard(id: 44, name: '', image: "$_cards/card16.png"),
  GameCard(id: 45, name: '', image: "$_cards/card17.png"),
  GameCard(id: 46, name: '', image: "$_cards/card18.png"),
  GameCard(id: 47, name: '', image: "$_cards/card19.png"),
  GameCard(id: 48, name: '', image: "$_cards/card20.png"),
];